#!/usr/bin/env python3
"""
Maintain a consolidated table of Kutumba Rao's BUY recommendations.

Data model
----------
Each processed episode drops a small machine-readable sidecar next to its
kutumba_rao markdown:

    output/kutumba_rao/<stem>.buys.json
    {
      "date": "2026-06-16",
      "video_id": "MCht7Xs4bL8",
      "title": "...",
      "buys": [
        {"stock": "CG Power", "price": "target ~1,500", "note": "..."},
        ...
      ]
    }

This script globs every *.buys.json, aggregates per stock, and (re)writes:

    output/kutumba_rao/buy_recommendations.md    (human table)
    output/kutumba_rao/buy_recommendations.csv   (machine table)

Aggregation is per stock (case/punctuation-insensitive key):
  - Times suggested = number of DISTINCT dates it was a buy
  - Last suggested  = most recent of those dates
  - Price / Summary = taken from that most recent episode

Idempotent: safe to run any time. New runs just add a new *.buys.json, then
re-run this (the pipeline calls rebuild_buy_table() automatically).
"""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path

DEFAULT_DIR = Path("output/kutumba_rao")


def _key(name: str) -> str:
    """Normalise a stock name so 'CG Power' == 'cg power.' across runs."""
    return re.sub(r"[^a-z0-9]+", "", name.lower())


def load_buy_records(kdir: Path) -> list[dict]:
    """Flatten every sidecar into one row per (stock, episode)."""
    rows = []
    for f in sorted(kdir.glob("*.buys.json")):
        try:
            doc = json.loads(f.read_text(encoding="utf-8"))
        except Exception:
            continue
        date = doc.get("date", "")
        for b in doc.get("buys", []):
            stock = (b.get("stock") or "").strip()
            if not stock:
                continue
            rows.append({
                "stock": stock,
                "date": date,
                "video_id": doc.get("video_id", ""),
                "price": (b.get("price") or "").strip(),
                "note": (b.get("note") or "").strip(),
            })
    return rows


def aggregate(rows: list[dict]) -> list[dict]:
    """One entry per stock with count-of-days + latest details."""
    by_stock: dict[str, dict] = {}
    for r in rows:
        k = _key(r["stock"])
        agg = by_stock.setdefault(k, {"stock": r["stock"], "dates": set(),
                                      "latest_date": "", "price": "", "note": ""})
        agg["dates"].add(r["date"])
        if r["date"] >= agg["latest_date"]:        # ISO dates sort lexically
            agg["latest_date"] = r["date"]
            agg["stock"] = r["stock"]               # prefer latest spelling
            agg["price"] = r["price"]
            agg["note"] = r["note"]
    out = []
    for agg in by_stock.values():
        dates = sorted(d for d in agg["dates"] if d)
        out.append({
            "stock": agg["stock"],
            "price": agg["price"],
            "note": agg["note"],
            "first_suggested": dates[0] if dates else "",
            "last_suggested": dates[-1] if dates else "",
            "times_suggested": len(dates),
            "all_dates": ",".join(dates),
        })
    # most-recently-suggested first, then most-frequently
    out.sort(key=lambda e: (e["last_suggested"], e["times_suggested"]), reverse=True)
    return out


def write_csv(entries: list[dict], path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["Stock", "Price/level", "Summary", "First suggested",
                    "Last suggested", "Times suggested (days)", "All dates"])
        for e in entries:
            w.writerow([e["stock"], e["price"], e["note"], e["first_suggested"],
                        e["last_suggested"], e["times_suggested"], e["all_dates"]])


def write_md(entries: list[dict], path: Path) -> None:
    lines = [
        "# Kutumba Rao — BUY recommendations (consolidated)",
        "",
        "_Auto-generated by `update_buy_table.py` from `*.buys.json` sidecars._  ",
        "_Buy = Buy / Add / Accumulate calls only. Price = as stated on the last "
        "date suggested (not a live quote)._",
        "",
        "| Stock | Price / level | What he said | Last suggested | Times suggested (days) |",
        "|-------|---------------|--------------|----------------|------------------------|",
    ]
    for e in entries:
        note = e["note"].replace("|", "\\|").replace("\n", " ")
        price = e["price"].replace("|", "\\|") or "—"
        lines.append(f"| {e['stock']} | {price} | {note} | {e['last_suggested']} "
                     f"| {e['times_suggested']} |")
    lines.append("")
    lines.append(f"_Total buy-rated stocks: {len(entries)}._")
    path.write_text("\n".join(lines), encoding="utf-8")


def rebuild_buy_table(kdir: Path = DEFAULT_DIR) -> int:
    """Regenerate buy_recommendations.{md,csv}. Returns the stock count."""
    kdir = Path(kdir)
    rows = load_buy_records(kdir)
    entries = aggregate(rows)
    write_csv(entries, kdir / "buy_recommendations.csv")
    write_md(entries, kdir / "buy_recommendations.md")
    return len(entries)


def main(argv=None) -> int:
    import argparse
    p = argparse.ArgumentParser(description="Rebuild Kutumba Rao buy-recommendations table.")
    p.add_argument("--dir", default=str(DEFAULT_DIR), help="kutumba_rao output dir")
    args = p.parse_args(argv)
    n = rebuild_buy_table(Path(args.dir))
    print(f"Wrote buy_recommendations.md / .csv ({n} stocks) in {args.dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
